version: '3.8'
services:
  web:
    image: 192.168.0.1:5000/app:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    ports:
      - "5001:5000"
  redis:
    image: redis:alpine
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  default:
    driver: overlay
